version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1234qwer
    ports:
     - '3000:3000'
    volumes:
     - ./grafana_data:/var/lib/grafana